### ISSUE TITLE
Adding lrtechfest speaker schedule

### ISSUE THREAD

**Issue by kwilson05** [Little-Rock-Tech-Fest/lrtechfest#12]
Hi,

Do you have any plans of adding an expected start time for each speaker?

It would be nice to know when each is talking at LRTechFest so people could plan their day accordingly. I understand if you don't have time for the change this year but it would be helpful for the future. Also, I wouldn't mind lending a hand to add this feature.

Thanks.

**Comment by curtisweeks** [comment]
Closing old issues. Speaker times are posted on the site each year. Thanks.
